language: java

jdk:
    - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/2.9/plugin-resolution/cache.properties.lock
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches